# -*- coding: utf-8 -*-
import re

def rep(filename, replacements):
    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    for old, new in replacements:
        if old not in content:
            print(f"WARNING: {old[:30]}... not found in {filename}")
        content = content.replace(old, new)
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)

# lam-sao-de-pick-up.html
pickup = [
    ('<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;">Hướng dẫn lấy món</span>', '<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;" data-i18n="pickupGuide">Hướng dẫn lấy món</span>'),
    ('<h1 class="split-title" style="justify-content: center;"><span>Làm sao để</span><span>nhận món?</span></h1>', '<h1 class="split-title" style="justify-content: center;"><span data-i18n="pickupHowTo">Làm sao để</span><span data-i18n="pickupReceive">nhận món?</span></h1>'),
    ('<p style="margin: 24px auto; max-width: 800px; font-size: 1.05rem; opacity: 0.9;">Đơn giản, nhanh chóng và thân thiện. Dưới đây là các bước để bạn lấy phần ăn đã đặt.</p>', '<p style="margin: 24px auto; max-width: 800px; font-size: 1.05rem; opacity: 0.9;" data-i18n="pickupDesc">Đơn giản, nhanh chóng và thân thiện. Dưới đây là các bước để bạn lấy phần ăn đã đặt.</p>'),
    ('<span class="eyebrow"\n        style="color: var(--green-800); background: var(--white); box-shadow: 0 8px 24px rgba(16, 60, 41, 0.06);">Quy trình nhận món</span>', '<span class="eyebrow"\n        style="color: var(--green-800); background: var(--white); box-shadow: 0 8px 24px rgba(16, 60, 41, 0.06);" data-i18n="pickupProcess">Quy trình nhận món</span>'),
    ('<h2 style="color: var(--green-900); margin-top: 24px;"><span>3 bước</span><span>tại cửa hàng</span></h2>', '<h2 style="color: var(--green-900); margin-top: 24px;"><span data-i18n="pickup3Steps">3 bước</span><span data-i18n="pickupAtStore">tại cửa hàng</span></h2>'),
    ('<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);">Bước 01</span>', '<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);" data-i18n="appStep1">Bước 01</span>'),
    ('<h2 class="split-title" style="color: var(--text);">Tới đúng giờ</h2>', '<h2 class="split-title" style="color: var(--text);" data-i18n="pickupStep1Title">Tới đúng giờ</h2>'),
    ('<p class="balanced-two-line" style="color: var(--muted);">Đến cửa hàng trong khung giờ nhận được thông báo trên ứng dụng.</p>', '<p class="balanced-two-line" style="color: var(--muted);" data-i18n="pickupStep1Desc">Đến cửa hàng trong khung giờ nhận được thông báo trên ứng dụng.</p>'),
    ('<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);">Bước 02</span>', '<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);" data-i18n="appStep2">Bước 02</span>'),
    ('<h2 class="split-title" style="color: var(--text);">Đưa mã cho nhân viên</h2>', '<h2 class="split-title" style="color: var(--text);" data-i18n="pickupStep2Title">Đưa mã cho nhân viên</h2>'),
    ('<p class="balanced-two-line" style="color: var(--muted);">Mở app, đưa mã QR hoặc mã đơn hàng cho nhân viên cửa hàng xác nhận.</p>', '<p class="balanced-two-line" style="color: var(--muted);" data-i18n="pickupStep2Desc">Mở app, đưa mã QR hoặc mã đơn hàng cho nhân viên cửa hàng xác nhận.</p>'),
    ('<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);">Bước 03</span>', '<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);" data-i18n="appStep3">Bước 03</span>'),
    ('<h2 class="split-title" style="color: var(--text);">Nhận phần ăn</h2>', '<h2 class="split-title" style="color: var(--text);" data-i18n="pickupStep3Title">Nhận phần ăn</h2>'),
    ('<p class="balanced-two-line" style="color: var(--muted);">Tận hưởng món ngon và tự hào vì bạn vừa giúp giảm lãng phí thực phẩm!</p>', '<p class="balanced-two-line" style="color: var(--muted);" data-i18n="pickupStep3Desc">Tận hưởng món ngon và tự hào vì bạn vừa giúp giảm lãng phí thực phẩm!</p>')
]
rep('lam-sao-de-pick-up.html', pickup)

# about-remeli.html
about = [
    ('<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;">Về chúng tôi</span>', '<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;" data-i18n="aboutUs">Về chúng tôi</span>'),
    ('<h1 class="split-title" style="justify-content: center;"><span>Câu chuyện</span><span>Remeli</span></h1>', '<h1 class="split-title" style="justify-content: center;"><span data-i18n="aboutStory">Câu chuyện</span><span data-i18n="aboutRemeli">Remeli</span></h1>'),
    ('<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;">Hành trình kết nối những bữa ăn ngon với sứ mệnh giảm thiểu lãng phí và bảo vệ môi trường Việt Nam.</p>', '<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;" data-i18n="aboutHeroDesc">Hành trình kết nối những bữa ăn ngon với sứ mệnh giảm thiểu lãng phí và bảo vệ môi trường Việt Nam.</p>'),
    ('<span class="eyebrow" style="background: var(--green-100); color: var(--green-800);">Ý tưởng khởi nguồn</span>', '<span class="eyebrow" style="background: var(--green-100); color: var(--green-800);" data-i18n="aboutIdea">Ý tưởng khởi nguồn</span>'),
    ('<h2 style="color: var(--green-900); font-size: 2.8rem; margin: 24px 0; font-family: var(--display-font); line-height: 1.2;">Cứu lấy thức ăn, bảo vệ Trái Đất</h2>', '<h2 style="color: var(--green-900); font-size: 2.8rem; margin: 24px 0; font-family: var(--display-font); line-height: 1.2;" data-i18n="aboutSaveFood">Cứu lấy thức ăn, bảo vệ Trái Đất</h2>'),
    ('<p style="color: var(--muted); font-size: 1.25rem; line-height: 1.8; margin-top: 24px;">Tại Việt Nam, hàng tấn thức ăn hoàn toàn ngon lành bị lãng phí mỗi ngày chỉ vì chưa tìm được người dùng kịp thời. Remeli ra đời với một khát vọng đơn giản: tạo ra một nền tảng kết nối các cửa hàng thực phẩm với những người yêu ẩm thực, giúp <strong>cứu lấy những bữa ăn ngon</strong>, tiết kiệm chi phí, và quan trọng nhất là <strong>giảm thiểu lượng khí thải carbon</strong> gây hiệu ứng nhà kính từ rác thải thực phẩm.</p>', '<p style="color: var(--muted); font-size: 1.25rem; line-height: 1.8; margin-top: 24px;" data-i18n="aboutVisionDesc">Tại Việt Nam, hàng tấn thức ăn hoàn toàn ngon lành bị lãng phí mỗi ngày chỉ vì chưa tìm được người dùng kịp thời. Remeli ra đời với một khát vọng đơn giản: tạo ra một nền tảng kết nối các cửa hàng thực phẩm với những người yêu ẩm thực, giúp <strong>cứu lấy những bữa ăn ngon</strong>, tiết kiệm chi phí, và quan trọng nhất là <strong>giảm thiểu lượng khí thải carbon</strong> gây hiệu ứng nhà kính từ rác thải thực phẩm.</p>'),
    ('<h2 class="split-title" style="color: var(--green-900); justify-content: center;"><span>Vì sao Remeli</span><span>ra đời?</span></h2>', '<h2 class="split-title" style="color: var(--green-900); justify-content: center;"><span data-i18n="aboutWhyRemeli">Vì sao Remeli</span><span data-i18n="aboutBorn">ra đời?</span></h2>'),
    ('<h3 style="color: var(--green-900); font-size: 1.5rem; margin-bottom: 16px;">Bảo vệ Môi trường</h3>', '<h3 style="color: var(--green-900); font-size: 1.5rem; margin-bottom: 16px;" data-i18n="aboutProtectEnv">Bảo vệ Môi trường</h3>'),
    ('<p style="color: var(--muted); line-height: 1.6; margin: 0; font-size: 1.05rem;">Mỗi phần ăn được cứu khỏi thùng rác đồng nghĩa với việc giảm thiểu lượng khí thải methane. Cùng nhau, chúng ta đang làm xanh lại bầu không khí của Việt Nam.</p>', '<p style="color: var(--muted); line-height: 1.6; margin: 0; font-size: 1.05rem;" data-i18n="aboutProtectEnvDesc">Mỗi phần ăn được cứu khỏi thùng rác đồng nghĩa với việc giảm thiểu lượng khí thải methane. Cùng nhau, chúng ta đang làm xanh lại bầu không khí của Việt Nam.</p>'),
    ('<h3 style="color: var(--green-900); font-size: 1.5rem; margin-bottom: 16px;">Chống Lãng phí</h3>', '<h3 style="color: var(--green-900); font-size: 1.5rem; margin-bottom: 16px;" data-i18n="aboutFightWaste">Chống Lãng phí</h3>'),
    ('<p style="color: var(--green-900); opacity: 0.9; line-height: 1.6; margin: 0; font-size: 1.05rem;">Chúng tôi tin rằng thức ăn ngon được tạo ra là để thưởng thức. Remeli giúp các nhà hàng tối ưu hoá nguồn nguyên liệu và không để phí phạm công sức đầu bếp.</p>', '<p style="color: var(--green-900); opacity: 0.9; line-height: 1.6; margin: 0; font-size: 1.05rem;" data-i18n="aboutFightWasteDesc">Chúng tôi tin rằng thức ăn ngon được tạo ra là để thưởng thức. Remeli giúp các nhà hàng tối ưu hoá nguồn nguyên liệu và không để phí phạm công sức đầu bếp.</p>'),
    ('<h3 style="color: var(--white); font-size: 1.5rem; margin-bottom: 16px;">Tiết kiệm & Gắn kết</h3>', '<h3 style="color: var(--white); font-size: 1.5rem; margin-bottom: 16px;" data-i18n="aboutSaveConnect">Tiết kiệm & Gắn kết</h3>'),
    ('<p style="color: var(--green-100); opacity: 0.9; line-height: 1.6; margin: 0; font-size: 1.05rem;">Người dùng được ăn ngon với mức giá ưu đãi, cửa hàng có thêm thu nhập, và cộng đồng xích lại gần nhau hơn trong một mục tiêu chung vô cùng ý nghĩa.</p>', '<p style="color: var(--green-100); opacity: 0.9; line-height: 1.6; margin: 0; font-size: 1.05rem;" data-i18n="aboutSaveConnectDesc">Người dùng được ăn ngon với mức giá ưu đãi, cửa hàng có thêm thu nhập, và cộng đồng xích lại gần nhau hơn trong một mục tiêu chung vô cùng ý nghĩa.</p>')
]
rep('about-remeli.html', about)

# our-team.html
team = [
    ('<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;">Đội ngũ</span>', '<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;" data-i18n="teamEyebrow2">Đội ngũ</span>'),
    ('<h1 class="split-title" style="justify-content: center;"><span>Người Việt</span><span>Kiến tạo</span></h1>', '<h1 class="split-title" style="justify-content: center;"><span data-i18n="teamVietnamese">Người Việt</span><span data-i18n="teamCreate">Kiến tạo</span></h1>'),
    ('<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;">Chúng tôi là tập hợp những con\n        người Việt Nam trẻ tuổi, đầy đam mê, cùng chung một khát vọng giải quyết bài toán chống lãng phí thực phẩm tại\n        quê hương mình.</p>', '<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;" data-i18n="teamVietnameseDesc">Chúng tôi là tập hợp những con\n        người Việt Nam trẻ tuổi, đầy đam mê, cùng chung một khát vọng giải quyết bài toán chống lãng phí thực phẩm tại\n        quê hương mình.</p>'),
    ('<span class="eyebrow"\n        style="color: var(--green-800); background: var(--white); box-shadow: 0 8px 24px rgba(16, 60, 41, 0.06);">Đội ngũ</span>', '<span class="eyebrow"\n        style="color: var(--green-800); background: var(--white); box-shadow: 0 8px 24px rgba(16, 60, 41, 0.06);" data-i18n="teamEyebrow2">Đội ngũ</span>'),
    ('<h2 style="color: var(--green-900); margin-top: 24px;">Những nhà sáng lập</h2>', '<h2 style="color: var(--green-900); margin-top: 24px;" data-i18n="teamFounders">Những nhà sáng lập</h2>'),
    ('<h3 class="team-name">Nguyễn Văn A</h3>', '<h3 class="team-name" data-i18n="teamName1">Nguyễn Văn A</h3>'),
    ('<p class="team-title">CEO & Founder</p>', '<p class="team-title" data-i18n="teamRole1">CEO & Founder</p>'),
    ('<h3 class="team-name">Trần Thị B</h3>', '<h3 class="team-name" data-i18n="teamName2">Trần Thị B</h3>'),
    ('<p class="team-title">Trưởng phòng Vận hành</p>', '<p class="team-title" data-i18n="teamOps">Trưởng phòng Vận hành</p>'),
    ('<h3 class="team-name">Lê Văn C</h3>', '<h3 class="team-name" data-i18n="teamName3">Lê Văn C</h3>'),
    ('<p class="team-title">Giám đốc Kỹ thuật</p>', '<p class="team-title" data-i18n="teamTech">Giám đốc Kỹ thuật</p>'),
    ('<h3 class="team-name">Phạm Thị D</h3>', '<h3 class="team-name" data-i18n="teamName4">Phạm Thị D</h3>'),
    ('<p class="team-title">Giám đốc Marketing</p>', '<p class="team-title" data-i18n="teamMkt">Giám đốc Marketing</p>')
]
rep('our-team.html', team)

# tac-dong.html
impact = [
    ('<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;">Tác động của Remeli</span>', '<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;" data-i18n="impactOfRemeli">Tác động của Remeli</span>'),
    ('<h1 class="split-title" style="justify-content: center;"><span>Lựa chọn nhỏ</span><span>Thay đổi lớn</span></h1>', '<h1 class="split-title" style="justify-content: center;"><span data-i18n="impactSmallChoice">Lựa chọn nhỏ</span><span data-i18n="impactBigChange">Thay đổi lớn</span></h1>'),
    ('<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;">Hành động tuy nhỏ bé của bạn đang từng bước tạo ra những tác động khổng lồ, góp phần bảo vệ hành tinh xanh của chúng ta.</p>', '<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;" data-i18n="impactHeroDesc">Hành động tuy nhỏ bé của bạn đang từng bước tạo ra những tác động khổng lồ, góp phần bảo vệ hành tinh xanh của chúng ta.</p>'),
    ('<h3 style="color: var(--green-900); font-size: 3rem; margin-bottom: 8px;">25K+</h3>', '<h3 style="color: var(--green-900); font-size: 3rem; margin-bottom: 8px;" data-i18n="impactMetric1">25K+</h3>'),
    ('<p style="color: var(--green-800); font-weight: 600; font-size: 1.2rem; margin-bottom: 12px;">Phần ăn được giải cứu</p>', '<p style="color: var(--green-800); font-weight: 600; font-size: 1.2rem; margin-bottom: 12px;" data-i18n="impactMealsSaved">Phần ăn được giải cứu</p>'),
    ('<p style="color: var(--muted); font-size: 0.95rem;">Hàng chục ngàn bữa ăn ngon miệng đã đến tay người dùng kịp thời thay vì kết thúc tại bãi rác.</p>', '<p style="color: var(--muted); font-size: 0.95rem;" data-i18n="impactMealsSavedDesc">Hàng chục ngàn bữa ăn ngon miệng đã đến tay người dùng kịp thời thay vì kết thúc tại bãi rác.</p>'),
    ('<h3 style="color: var(--green-900); font-size: 3rem; margin-bottom: 8px;">8.4T</h3>', '<h3 style="color: var(--green-900); font-size: 3rem; margin-bottom: 8px;" data-i18n="impactMetric2">8.4T</h3>'),
    ('<p style="color: var(--green-800); font-weight: 600; font-size: 1.2rem; margin-bottom: 12px;">CO₂e được ngăn chặn</p>', '<p style="color: var(--green-800); font-weight: 600; font-size: 1.2rem; margin-bottom: 12px;" data-i18n="impactCO2">CO₂e được ngăn chặn</p>'),
    ('<p style="color: var(--muted); font-size: 0.95rem;">Lượng khí thải carbon tương đương (CO₂e) khổng lồ được cắt giảm từ việc ngăn chặn rác thải.</p>', '<p style="color: var(--muted); font-size: 0.95rem;" data-i18n="impactCO2Desc">Lượng khí thải carbon tương đương (CO₂e) khổng lồ được cắt giảm từ việc ngăn chặn rác thải.</p>'),
    ('<h3 style="color: var(--green-900); font-size: 3rem; margin-bottom: 8px;">15.2T</h3>', '<h3 style="color: var(--green-900); font-size: 3rem; margin-bottom: 8px;" data-i18n="impactMetric3">15.2T</h3>'),
    ('<p style="color: var(--green-800); font-weight: 600; font-size: 1.2rem; margin-bottom: 12px;">kg thức ăn được cứu</p>', '<p style="color: var(--green-800); font-weight: 600; font-size: 1.2rem; margin-bottom: 12px;" data-i18n="impactKgSaved">kg thức ăn được cứu</p>'),
    ('<p style="color: var(--muted); font-size: 0.95rem;">15.2 Tấn (tương đương 15,200 kg) nguyên liệu tươi ngon đã không bị lãng phí vô ích.</p>', '<p style="color: var(--muted); font-size: 0.95rem;" data-i18n="impactKgSavedDesc">15.2 Tấn (tương đương 15,200 kg) nguyên liệu tươi ngon đã không bị lãng phí vô ích.</p>'),
    ('<span class="eyebrow" style="background: rgba(255,255,255,0.2); color: var(--white);">Tầm nhìn bền vững</span>', '<span class="eyebrow" style="background: rgba(255,255,255,0.2); color: var(--white);" data-i18n="impactVision">Tầm nhìn bền vững</span>'),
    ('<h2 class="split-title" style="justify-content: center; color: var(--white);"><span>Mỗi phần ăn được cứu</span><span>là một bước tiến vì Trái Đất</span></h2>', '<h2 class="split-title" style="justify-content: center; color: var(--white);"><span data-i18n="impactEveryMeal">Mỗi phần ăn được cứu</span><span data-i18n="impactStepForEarth">là một bước tiến vì Trái Đất</span></h2>'),
    ('<p style="max-width: 900px; margin: 32px auto 0; font-size: 1.2rem; line-height: 1.8; color: rgba(255,255,255,0.9);">Lãng phí thực phẩm không chỉ là bài toán về kinh tế mà còn là gánh nặng khổng lồ đối với môi trường. Khi thức ăn bị vứt bỏ, toàn bộ năng lượng và nguồn tài nguyên nước dùng để gieo trồng, thu hoạch, vận chuyển và đóng gói cũng đều biến mất. Bằng việc đồng hành cùng Remeli, bạn đang góp phần vào một chuỗi cung ứng thực phẩm tuần hoàn, nơi mọi giá trị đều được trân trọng và Trái Đất được giảm tải áp lực.</p>', '<p style="max-width: 900px; margin: 32px auto 0; font-size: 1.2rem; line-height: 1.8; color: rgba(255,255,255,0.9);" data-i18n="impactVisionDesc">Lãng phí thực phẩm không chỉ là bài toán về kinh tế mà còn là gánh nặng khổng lồ đối với môi trường. Khi thức ăn bị vứt bỏ, toàn bộ năng lượng và nguồn tài nguyên nước dùng để gieo trồng, thu hoạch, vận chuyển và đóng gói cũng đều biến mất. Bằng việc đồng hành cùng Remeli, bạn đang góp phần vào một chuỗi cung ứng thực phẩm tuần hoàn, nơi mọi giá trị đều được trân trọng và Trái Đất được giảm tải áp lực.</p>'),
    ('<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);">Tác động Môi trường</span>', '<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);" data-i18n="impactEnvTitle">Tác động Môi trường</span>'),
    ('<h2 class="split-title" style="color: var(--text);"><span>Giảm thiểu</span><span>Khí nhà kính</span></h2>', '<h2 class="split-title" style="color: var(--text);"><span data-i18n="impactReduce">Giảm thiểu</span><span data-i18n="impactGreenhouse">Khí nhà kính</span></h2>'),
    ('<p style="color: var(--muted); font-size: 1.1rem; line-height: 1.7;">Thực phẩm khi bị chôn lấp sẽ sinh ra lượng lớn khí methane - loại khí gây hiệu ứng nhà kính mạnh gấp 25 lần so với CO₂. Bằng việc cứu lấy thức ăn, chúng ta trực tiếp ngăn chặn sự nóng lên toàn cầu và bảo vệ bầu không khí trong lành cho thế hệ tương lai.</p>', '<p style="color: var(--muted); font-size: 1.1rem; line-height: 1.7;" data-i18n="impactEnvDesc">Thực phẩm khi bị chôn lấp sẽ sinh ra lượng lớn khí methane - loại khí gây hiệu ứng nhà kính mạnh gấp 25 lần so với CO₂. Bằng việc cứu lấy thức ăn, chúng ta trực tiếp ngăn chặn sự nóng lên toàn cầu và bảo vệ bầu không khí trong lành cho thế hệ tương lai.</p>'),
    ('<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);">Tác động Kinh tế</span>', '<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);" data-i18n="impactEconTitle">Tác động Kinh tế</span>'),
    ('<h2 class="split-title" style="color: var(--text);"><span>Tối ưu hoá</span><span>Nguồn lực</span></h2>', '<h2 class="split-title" style="color: var(--text);"><span data-i18n="impactOptimize">Tối ưu hoá</span><span data-i18n="impactResources">Nguồn lực</span></h2>'),
    ('<p style="color: var(--muted); font-size: 1.1rem; line-height: 1.7;">Mọi nguyên liệu, nhân công và năng lượng để sản xuất ra một món ăn đều đáng giá. Remeli giúp các doanh nghiệp và nhà hàng thu hồi được chi phí sản xuất, đồng thời mang đến cho người tiêu dùng những bữa ăn chất lượng với mức giá vô cùng hợp lý.</p>', '<p style="color: var(--muted); font-size: 1.1rem; line-height: 1.7;" data-i18n="impactEconDesc">Mọi nguyên liệu, nhân công và năng lượng để sản xuất ra một món ăn đều đáng giá. Remeli giúp các doanh nghiệp và nhà hàng thu hồi được chi phí sản xuất, đồng thời mang đến cho người tiêu dùng những bữa ăn chất lượng với mức giá vô cùng hợp lý.</p>'),
    ('<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);">Tác động Xã hội</span>', '<span class="eyebrow" style="color: var(--green-700); background: var(--green-100);" data-i18n="impactSocialTitle">Tác động Xã hội</span>'),
    ('<h2 class="split-title" style="color: var(--text);"><span>Gắn kết</span><span>Cộng đồng</span></h2>', '<h2 class="split-title" style="color: var(--text);"><span data-i18n="impactConnect">Gắn kết</span><span data-i18n="impactCommunity">Cộng đồng</span></h2>'),
    ('<p style="color: var(--muted); font-size: 1.1rem; line-height: 1.7;">Không chỉ dừng lại ở việc mua bán, Remeli đang xây dựng một cộng đồng những người tiêu dùng có ý thức trách nhiệm cao. Chúng ta kết nối với nhau, với cửa hàng địa phương bằng một thông điệp tích cực: Sống xanh, tiêu dùng thông minh và trân trọng thức ăn.</p>', '<p style="color: var(--muted); font-size: 1.1rem; line-height: 1.7;" data-i18n="impactSocialDesc">Không chỉ dừng lại ở việc mua bán, Remeli đang xây dựng một cộng đồng những người tiêu dùng có ý thức trách nhiệm cao. Chúng ta kết nối với nhau, với cửa hàng địa phương bằng một thông điệp tích cực: Sống xanh, tiêu dùng thông minh và trân trọng thức ăn.</p>'),
    ('<h2 style="color: var(--green-900); font-size: 2.8rem; margin: 24px 0;"><span>Trở thành một phần</span><br/><span style="color: var(--yellow);">của giải pháp</span></h2>', '<h2 style="color: var(--green-900); font-size: 2.8rem; margin: 24px 0;"><span data-i18n="impactBePart">Trở thành một phần</span><br/><span style="color: var(--yellow);" data-i18n="impactOfSolution">của giải pháp</span></h2>'),
    ('<p style="color: var(--muted); font-size: 1.15rem; max-width: 600px; margin: 0 auto 40px; line-height: 1.6;">Tải Remeli ngay hôm nay để bắt đầu hành trình giải cứu thức ăn và bảo vệ môi trường cùng hàng chục ngàn người Việt Nam khác.</p>', '<p style="color: var(--muted); font-size: 1.15rem; max-width: 600px; margin: 0 auto 40px; line-height: 1.6;" data-i18n="impactCtaDesc">Tải Remeli ngay hôm nay để bắt đầu hành trình giải cứu thức ăn và bảo vệ môi trường cùng hàng chục ngàn người Việt Nam khác.</p>'),
    ('<span style="position:relative; z-index:2;">Tải Ứng Dụng Ngay</span>', '<span style="position:relative; z-index:2;" data-i18n="impactCtaBtn">Tải Ứng Dụng Ngay</span>')
]
rep('tac-dong.html', impact)

# phan-hoi-khach-hang.html
feedback = [
    ('<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;">Cộng đồng Remeli</span>', '<span class="eyebrow eyebrow-yellow" style="margin: 0 auto 16px;" data-i18n="fbCommunity">Cộng đồng Remeli</span>'),
    ('<h1 class="split-title" style="justify-content: center;"><span>Tiếng nói từ</span><span>Cộng đồng</span></h1>', '<h1 class="split-title" style="justify-content: center;"><span data-i18n="fbVoice">Tiếng nói từ</span><span data-i18n="fbComm">Cộng đồng</span></h1>'),
    ('<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;">Khám phá những trải nghiệm chân thực nhất từ hàng ngàn khách hàng và đối tác đã đồng hành cùng Remeli trên hành trình chống lãng phí.</p>', '<p style="margin: 24px auto; max-width: 800px; font-size: 1.15rem; opacity: 0.9;" data-i18n="fbDesc">Khám phá những trải nghiệm chân thực nhất từ hàng ngàn khách hàng và đối tác đã đồng hành cùng Remeli trên hành trình chống lãng phí.</p>'),
    ('<span class="eyebrow"\n        style="color: var(--green-800); background: var(--white); box-shadow: 0 8px 24px rgba(16, 60, 41, 0.06);">Cảm nhận thực tế</span>', '<span class="eyebrow"\n        style="color: var(--green-800); background: var(--white); box-shadow: 0 8px 24px rgba(16, 60, 41, 0.06);" data-i18n="fbRealExp">Cảm nhận thực tế</span>'),
    ('<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;">Bí kíp ăn ngon, giá hời!</h3>', '<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;" data-i18n="fbTitle1">Bí kíp ăn ngon, giá hời!</h3>'),
    ('<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;">"App siêu tiện lợi luôn! Mình hay canh giờ tối để đặt túi mù từ tiệm bánh yêu thích. Vừa được ăn ngon, vừa tiết kiệm được kha khá tiền, cảm giác bóc quà bất ngờ lắm!"</p>', '<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;" data-i18n="fbText1">"App siêu tiện lợi luôn! Mình hay canh giờ tối để đặt túi mù từ tiệm bánh yêu thích. Vừa được ăn ngon, vừa tiết kiệm được kha khá tiền, cảm giác bóc quà bất ngờ lắm!"</p>'),
    ('<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;">Thảo Nguyễn</strong>', '<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;" data-i18n="fbName1">Thảo Nguyễn</strong>'),
    ('<span style="color: var(--muted); font-size: 0.9rem;">Người dùng • TP. HCM</span>', '<span style="color: var(--muted); font-size: 0.9rem;" data-i18n="fbRole1">Người dùng • TP. HCM</span>'),
    ('<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;">Cứu cánh cuối tháng</h3>', '<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;" data-i18n="fbTitle2">Cứu cánh cuối tháng</h3>'),
    ('<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;">"Là sinh viên nên Remeli cứu rỗi ví tiền của mình rất nhiều. Thức ăn vẫn còn rất nóng hổi và chất lượng, hy vọng app mở rộng thêm nhiều cửa hàng gần trường mình hơn."</p>', '<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;" data-i18n="fbText2">"Là sinh viên nên Remeli cứu rỗi ví tiền của mình rất nhiều. Thức ăn vẫn còn rất nóng hổi và chất lượng, hy vọng app mở rộng thêm nhiều cửa hàng gần trường mình hơn."</p>'),
    ('<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;">Hoàng Hải</strong>', '<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;" data-i18n="fbName2">Hoàng Hải</strong>'),
    ('<span style="color: var(--muted); font-size: 0.9rem;">Sinh viên • Hà Nội</span>', '<span style="color: var(--muted); font-size: 0.9rem;" data-i18n="fbRole2">Sinh viên • Hà Nội</span>'),
    ('<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;">Giải pháp chống lãng phí</h3>', '<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;" data-i18n="fbTitle3">Giải pháp chống lãng phí</h3>'),
    ('<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;">"Từ ngày đăng ký bán phần ăn cuối ngày trên Remeli, quán tôi không còn phải bỏ mứa đồ ăn nữa. Doanh thu tăng nhẹ nhưng vui nhất là không lãng phí công sức nấu nướng."</p>', '<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;" data-i18n="fbText3">"Từ ngày đăng ký bán phần ăn cuối ngày trên Remeli, quán tôi không còn phải bỏ mứa đồ ăn nữa. Doanh thu tăng nhẹ nhưng vui nhất là không lãng phí công sức nấu nướng."</p>'),
    ('<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;">Cơm Tấm Mười</strong>', '<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;" data-i18n="fbName3">Cơm Tấm Mười</strong>'),
    ('<span style="color: var(--muted); font-size: 0.9rem;">Đối tác • Quận 3</span>', '<span style="color: var(--muted); font-size: 0.9rem;" data-i18n="fbRole3">Đối tác • Quận 3</span>'),
    ('<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;">Hành động nhỏ, ý nghĩa lớn</h3>', '<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;" data-i18n="fbTitle4">Hành động nhỏ, ý nghĩa lớn</h3>'),
    ('<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;">"Thật tuyệt vời khi được chung tay bảo vệ môi trường mỗi ngày chỉ bằng những bữa ăn ngon. Thiết kế app cực kỳ dễ thương và dễ sử dụng!"</p>', '<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;" data-i18n="fbText4">"Thật tuyệt vời khi được chung tay bảo vệ môi trường mỗi ngày chỉ bằng những bữa ăn ngon. Thiết kế app cực kỳ dễ thương và dễ sử dụng!"</p>'),
    ('<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;">Mai Lan</strong>', '<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;" data-i18n="fbName4">Mai Lan</strong>'),
    ('<span style="color: var(--muted); font-size: 0.9rem;">Người dùng • Đà Nẵng</span>', '<span style="color: var(--muted); font-size: 0.9rem;" data-i18n="fbRole4">Người dùng • Đà Nẵng</span>'),
    ('<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;">Tiện lợi, mượt mà</h3>', '<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;" data-i18n="fbTitle5">Tiện lợi, mượt mà</h3>'),
    ('<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;">"Tính năng pick-up của app hoạt động cực kỳ mượt mà. Mình tan làm ghé ngang cửa hàng, chỉ cần đưa mã quét là nhận đồ ngay, không phải chờ đợi phút nào."</p>', '<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;" data-i18n="fbText5">"Tính năng pick-up của app hoạt động cực kỳ mượt mà. Mình tan làm ghé ngang cửa hàng, chỉ cần đưa mã quét là nhận đồ ngay, không phải chờ đợi phút nào."</p>'),
    ('<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;">Phan Anh</strong>', '<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;" data-i18n="fbName5">Phan Anh</strong>'),
    ('<span style="color: var(--muted); font-size: 0.9rem;">Nhân viên văn phòng • TP.HCM</span>', '<span style="color: var(--muted); font-size: 0.9rem;" data-i18n="fbRole5">Nhân viên văn phòng • TP.HCM</span>'),
    ('<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;">Niềm vui người thợ bánh</h3>', '<h3 style="color: var(--green-900); font-size: 1.4rem; margin-bottom: 12px;" data-i18n="fbTitle6">Niềm vui người thợ bánh</h3>'),
    ('<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;">"Không còn đau đầu vì bánh tồn kho mỗi tối, tôi cảm thấy rất biết ơn đội ngũ Remeli đã tạo ra một nền tảng thực sự ý nghĩa cho xã hội."</p>', '<p style="color: var(--muted); line-height: 1.6; margin-bottom: 24px;" data-i18n="fbText6">"Không còn đau đầu vì bánh tồn kho mỗi tối, tôi cảm thấy rất biết ơn đội ngũ Remeli đã tạo ra một nền tảng thực sự ý nghĩa cho xã hội."</p>'),
    ('<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;">Lò Bánh Tươi</strong>', '<strong style="display: block; color: var(--green-900); font-size: 1.1rem; margin-bottom: 4px;" data-i18n="fbName6">Lò Bánh Tươi</strong>'),
    ('<span style="color: var(--muted); font-size: 0.9rem;">Chủ tiệm bánh • Hà Nội</span>', '<span style="color: var(--muted); font-size: 0.9rem;" data-i18n="fbRole6">Chủ tiệm bánh • Hà Nội</span>')
]
rep('phan-hoi-khach-hang.html', feedback)
