import os

vi_strings = """
    // App Instructions
    appDownloadApp: 'Tải ứng dụng',
    appGetStarted: 'Bắt đầu với',
    appRemeli: 'Remeli',
    appHeroDesc: 'Khám phá các phần ăn ngon cuối ngày từ các nhà hàng xung quanh bạn.<br />Tải ứng dụng trên App Store hoặc Google Play ngay hôm nay!',
    appSmooth: 'Trải nghiệm mượt mà',
    appJustOneMin: 'Chỉ 1 phút',
    appToStart: 'để bắt đầu',
    appNoComplex: 'Bạn không cần tạo tài khoản phức tạp. Đăng nhập bằng Apple, Google hoặc số điện thoại chỉ trong vài giây.',
    appStep1Title: 'Tải ứng dụng',
    appStep1Desc: 'Tìm Remeli trên kho ứng dụng App Store hoặc Google Play và cài đặt hoàn toàn miễn phí.',
    appStep2Title: 'Đăng nhập nhanh',
    appStep2Desc: 'Sử dụng tài khoản Google, Apple hoặc số điện thoại để vào app ngay lập tức.',
    appStep3Title: 'Khám phá',
    appStep3Desc: 'Bật định vị để xem ngay các cửa hàng đang có phần ăn hấp dẫn xung quanh bạn.',

    // Pickup Guide
    pickupGuide: 'Hướng dẫn lấy món',
    pickupHowTo: 'Làm sao để',
    pickupReceive: 'nhận món?',
    pickupDesc: 'Đơn giản, nhanh chóng và thân thiện. Dưới đây là các bước để bạn lấy phần ăn đã đặt.',
    pickupProcess: 'Quy trình nhận món',
    pickup3Steps: '3 bước',
    pickupAtStore: 'tại cửa hàng',
    pickupStep1Title: 'Tới đúng giờ',
    pickupStep1Desc: 'Đến cửa hàng trong khung giờ nhận được thông báo trên ứng dụng.',
    pickupStep2Title: 'Đưa mã cho nhân viên',
    pickupStep2Desc: 'Mở app, đưa mã QR hoặc mã đơn hàng cho nhân viên cửa hàng xác nhận.',
    pickupStep3Title: 'Nhận phần ăn',
    pickupStep3Desc: 'Tận hưởng món ngon và tự hào vì bạn vừa giúp giảm lãng phí thực phẩm!',

    // About Remeli
    aboutUs: 'Về chúng tôi',
    aboutStory: 'Câu chuyện',
    aboutRemeli: 'Remeli',
    aboutHeroDesc: 'Hành trình kết nối những bữa ăn ngon với sứ mệnh giảm thiểu lãng phí và bảo vệ môi trường Việt Nam.',
    aboutIdea: 'Ý tưởng khởi nguồn',
    aboutSaveFood: 'Cứu lấy thức ăn, bảo vệ Trái Đất',
    aboutVisionDesc: 'Tại Việt Nam, hàng tấn thức ăn hoàn toàn ngon lành bị lãng phí mỗi ngày chỉ vì chưa tìm được người dùng kịp thời. Remeli ra đời với một khát vọng đơn giản: tạo ra một nền tảng kết nối các cửa hàng thực phẩm với những người yêu ẩm thực, giúp <strong>cứu lấy những bữa ăn ngon</strong>, tiết kiệm chi phí, và quan trọng nhất là <strong>giảm thiểu lượng khí thải carbon</strong> gây hiệu ứng nhà kính từ rác thải thực phẩm.',
    aboutWhyRemeli: 'Vì sao Remeli',
    aboutBorn: 'ra đời?',
    aboutProtectEnv: 'Bảo vệ Môi trường',
    aboutProtectEnvDesc: 'Mỗi phần ăn được cứu khỏi thùng rác đồng nghĩa với việc giảm thiểu lượng khí thải methane. Cùng nhau, chúng ta đang làm xanh lại bầu không khí của Việt Nam.',
    aboutFightWaste: 'Chống Lãng phí',
    aboutFightWasteDesc: 'Chúng tôi tin rằng thức ăn ngon được tạo ra là để thưởng thức. Remeli giúp các nhà hàng tối ưu hoá nguồn nguyên liệu và không để phí phạm công sức đầu bếp.',
    aboutSaveConnect: 'Tiết kiệm & Gắn kết',
    aboutSaveConnectDesc: 'Người dùng được ăn ngon với mức giá ưu đãi, cửa hàng có thêm thu nhập, và cộng đồng xích lại gần nhau hơn trong một mục tiêu chung vô cùng ý nghĩa.',

    // Our Team
    teamEyebrow: 'Đội ngũ Remeli',
    teamPeople: 'Những người',
    teamBehind: 'đứng sau Remeli',
    teamDesc: 'Một nhóm những người trẻ đam mê công nghệ, ẩm thực và môi trường, chung tay vì một Việt Nam xanh hơn.',
    teamVision: 'Tầm nhìn chung',
    teamNotJustApp: 'Chúng tôi không chỉ',
    teamMakingApp: 'làm một ứng dụng',
    teamVisionDesc: 'Chúng tôi đang xây dựng một cộng đồng những người quan tâm đến bữa ăn của mình và môi trường xung quanh. Mục tiêu là biến việc "cứu" thức ăn trở thành một thói quen hàng ngày của mọi người.',
    teamVietnamese: 'Người Việt',
    teamCreate: 'Kiến tạo',
    teamVietnameseDesc: 'Chúng tôi là tập hợp những con người Việt Nam trẻ tuổi, đầy đam mê, cùng chung một khát vọng giải quyết bài toán chống lãng phí thực phẩm tại quê hương mình.',
    teamFounders: 'Những nhà sáng lập',
    teamOps: 'Trưởng phòng Vận hành',
    teamTech: 'Giám đốc Kỹ thuật',
    teamMkt: 'Giám đốc Marketing',

    // Impact
    impactOfRemeli: 'Tác động của Remeli',
    impactSmallChoice: 'Lựa chọn nhỏ',
    impactBigChange: 'Thay đổi lớn',
    impactHeroDesc: 'Hành động tuy nhỏ bé của bạn đang từng bước tạo ra những tác động khổng lồ, góp phần bảo vệ hành tinh xanh của chúng ta.',
    impactMealsSaved: 'Phần ăn được giải cứu',
    impactMealsSavedDesc: 'Hàng chục ngàn bữa ăn ngon miệng đã đến tay người dùng kịp thời thay vì kết thúc tại bãi rác.',
    impactCO2: 'CO₂e được ngăn chặn',
    impactCO2Desc: 'Lượng khí thải carbon tương đương (CO₂e) khổng lồ được cắt giảm từ việc ngăn chặn rác thải.',
    impactKgSaved: 'kg thức ăn được cứu',
    impactKgSavedDesc: '15.2 Tấn (tương đương 15,200 kg) nguyên liệu tươi ngon đã không bị lãng phí vô ích.',
    impactVision: 'Tầm nhìn bền vững',
    impactEveryMeal: 'Mỗi phần ăn được cứu',
    impactStepForEarth: 'là một bước tiến vì Trái Đất',
    impactVisionDesc: 'Lãng phí thực phẩm không chỉ là bài toán về kinh tế mà còn là gánh nặng khổng lồ đối với môi trường. Khi thức ăn bị vứt bỏ, toàn bộ năng lượng và nguồn tài nguyên nước dùng để gieo trồng, thu hoạch, vận chuyển và đóng gói cũng đều biến mất. Bằng việc đồng hành cùng Remeli, bạn đang góp phần vào một chuỗi cung ứng thực phẩm tuần hoàn, nơi mọi giá trị đều được trân trọng và Trái Đất được giảm tải áp lực.',
    impactEnvTitle: 'Tác động Môi trường',
    impactReduce: 'Giảm thiểu',
    impactGreenhouse: 'Khí nhà kính',
    impactEnvDesc: 'Thực phẩm khi bị chôn lấp sẽ sinh ra lượng lớn khí methane - loại khí gây hiệu ứng nhà kính mạnh gấp 25 lần so với CO₂. Bằng việc cứu lấy thức ăn, chúng ta trực tiếp ngăn chặn sự nóng lên toàn cầu và bảo vệ bầu không khí trong lành cho thế hệ tương lai.',
    impactEconTitle: 'Tác động Kinh tế',
    impactOptimize: 'Tối ưu hoá',
    impactResources: 'Nguồn lực',
    impactEconDesc: 'Mọi nguyên liệu, nhân công và năng lượng để sản xuất ra một món ăn đều đáng giá. Remeli giúp các doanh nghiệp và nhà hàng thu hồi được chi phí sản xuất, đồng thời mang đến cho người tiêu dùng những bữa ăn chất lượng với mức giá vô cùng hợp lý.',
    impactSocialTitle: 'Tác động Xã hội',
    impactConnect: 'Gắn kết',
    impactCommunity: 'Cộng đồng',
    impactSocialDesc: 'Không chỉ dừng lại ở việc mua bán, Remeli đang xây dựng một cộng đồng những người tiêu dùng có ý thức trách nhiệm cao. Chúng ta kết nối với nhau, với cửa hàng địa phương bằng một thông điệp tích cực: Sống xanh, tiêu dùng thông minh và trân trọng thức ăn.',
    impactBePart: 'Trở thành một phần',
    impactOfSolution: 'của giải pháp',
    impactCtaDesc: 'Tải Remeli ngay hôm nay để bắt đầu hành trình giải cứu thức ăn và bảo vệ môi trường cùng hàng chục ngàn người Việt Nam khác.',
    impactCtaBtn: 'Tải Ứng Dụng Ngay',

    // Feedback
    fbCommunity: 'Cộng đồng Remeli',
    fbVoice: 'Tiếng nói từ',
    fbComm: 'Cộng đồng',
    fbDesc: 'Khám phá những trải nghiệm chân thực nhất từ hàng ngàn khách hàng và đối tác đã đồng hành cùng Remeli trên hành trình chống lãng phí.',
    fbRealExp: 'Cảm nhận thực tế',
    fbTitle1: 'Bí kíp ăn ngon, giá hời!',
    fbText1: '"App siêu tiện lợi luôn! Mình hay canh giờ tối để đặt túi mù từ tiệm bánh yêu thích. Vừa được ăn ngon, vừa tiết kiệm được kha khá tiền, cảm giác bóc quà bất ngờ lắm!"',
    fbRole1: 'Người dùng • TP. HCM',
    fbTitle2: 'Cứu cánh cuối tháng',
    fbText2: '"Là sinh viên nên Remeli cứu rỗi ví tiền của mình rất nhiều. Thức ăn vẫn còn rất nóng hổi và chất lượng, hy vọng app mở rộng thêm nhiều cửa hàng gần trường mình hơn."',
    fbRole2: 'Sinh viên • Hà Nội',
    fbTitle3: 'Giải pháp chống lãng phí',
    fbText3: '"Từ ngày đăng ký bán phần ăn cuối ngày trên Remeli, quán tôi không còn phải bỏ mứa đồ ăn nữa. Doanh thu tăng nhẹ nhưng vui nhất là không lãng phí công sức nấu nướng."',
    fbRole3: 'Đối tác • Quận 3',
    fbTitle4: 'Hành động nhỏ, ý nghĩa lớn',
    fbText4: '"Thật tuyệt vời khi được chung tay bảo vệ môi trường mỗi ngày chỉ bằng những bữa ăn ngon. Thiết kế app cực kỳ dễ thương và dễ sử dụng!"',
    fbRole4: 'Người dùng • Đà Nẵng',
    fbTitle5: 'Tiện lợi, mượt mà',
    fbText5: '"Tính năng pick-up của app hoạt động cực kỳ mượt mà. Mình tan làm ghé ngang cửa hàng, chỉ cần đưa mã quét là nhận đồ ngay, không phải chờ đợi phút nào."',
    fbRole5: 'Nhân viên văn phòng • TP.HCM',
    fbTitle6: 'Niềm vui người thợ bánh',
    fbText6: '"Không còn đau đầu vì bánh tồn kho mỗi tối, tôi cảm thấy rất biết ơn đội ngũ Remeli đã tạo ra một nền tảng thực sự ý nghĩa cho xã hội."',
    fbRole6: 'Chủ tiệm bánh • Hà Nội',
"""

en_strings = """
    // App Instructions
    appDownloadApp: 'Download app',
    appGetStarted: 'Get started with',
    appRemeli: 'Remeli',
    appHeroDesc: 'Discover delicious surplus food from nearby restaurants.<br />Download the app on the App Store or Google Play today!',
    appSmooth: 'Smooth experience',
    appJustOneMin: 'Just 1 minute',
    appToStart: 'to get started',
    appNoComplex: 'No complex account creation. Sign in with Apple, Google, or phone number in seconds.',
    appStep1Title: 'Download the app',
    appStep1Desc: 'Find Remeli on the App Store or Google Play and install it for free.',
    appStep2Title: 'Quick login',
    appStep2Desc: 'Use your Google, Apple account or phone number to sign in instantly.',
    appStep3Title: 'Discover',
    appStep3Desc: 'Turn on location to find stores with great food around you.',

    // Pickup Guide
    pickupGuide: 'Pickup Guide',
    pickupHowTo: 'How to',
    pickupReceive: 'pick up?',
    pickupDesc: 'Simple, fast, and friendly. Here are the steps to collect your order.',
    pickupProcess: 'Pickup process',
    pickup3Steps: '3 steps',
    pickupAtStore: 'at the store',
    pickupStep1Title: 'Arrive on time',
    pickupStep1Desc: 'Go to the store within the pickup window shown in the app.',
    pickupStep2Title: 'Show code to staff',
    pickupStep2Desc: 'Open the app, show the QR code or order code to the staff.',
    pickupStep3Title: 'Collect food',
    pickupStep3Desc: 'Enjoy delicious food and be proud that you helped reduce food waste!',

    // About Remeli
    aboutUs: 'About Us',
    aboutStory: 'The Story of',
    aboutRemeli: 'Remeli',
    aboutHeroDesc: 'A journey connecting delicious meals with the mission of reducing waste and protecting Vietnam\\'s environment.',
    aboutIdea: 'The Founding Idea',
    aboutSaveFood: 'Save food, protect the Earth',
    aboutVisionDesc: 'In Vietnam, tons of perfectly good food are wasted every day because they don\\'t reach consumers in time. Remeli was founded with a simple goal: to create a platform connecting food stores with food lovers, helping <strong>save delicious meals</strong>, save money, and most importantly <strong>reduce greenhouse gas emissions</strong> from food waste.',
    aboutWhyRemeli: 'Why was Remeli',
    aboutBorn: 'created?',
    aboutProtectEnv: 'Protect the Environment',
    aboutProtectEnvDesc: 'Every meal saved from the bin means reducing methane emissions. Together, we are making the air in Vietnam greener.',
    aboutFightWaste: 'Fight Food Waste',
    aboutFightWasteDesc: 'We believe good food is meant to be eaten. Remeli helps restaurants optimize ingredients and respect the chefs\\' efforts.',
    aboutSaveConnect: 'Save & Connect',
    aboutSaveConnectDesc: 'Users enjoy good food at affordable prices, stores earn extra income, and the community unites for a meaningful goal.',

    // Our Team
    teamEyebrow: 'Remeli Team',
    teamPeople: 'The people',
    teamBehind: 'behind Remeli',
    teamDesc: 'A group of young people passionate about technology, food, and the environment, working together for a greener Vietnam.',
    teamVision: 'Shared Vision',
    teamNotJustApp: 'We are not just',
    teamMakingApp: 'building an app',
    teamVisionDesc: 'We are building a community of people who care about their meals and the environment. Our goal is to make "rescuing" food a daily habit for everyone.',
    teamVietnamese: 'Vietnamese',
    teamCreate: 'Creators',
    teamVietnameseDesc: 'We are young, passionate Vietnamese individuals sharing a desire to solve the food waste problem in our hometown.',
    teamFounders: 'The Founders',
    teamOps: 'Head of Operations',
    teamTech: 'Chief Technology Officer',
    teamMkt: 'Chief Marketing Officer',

    // Impact
    impactOfRemeli: 'Impact of Remeli',
    impactSmallChoice: 'Small choice',
    impactBigChange: 'Big impact',
    impactHeroDesc: 'Your small action creates a huge impact, contributing to protecting our green planet.',
    impactMealsSaved: 'Meals saved',
    impactMealsSavedDesc: 'Tens of thousands of delicious meals reached users in time instead of ending up in landfills.',
    impactCO2: 'CO₂e prevented',
    impactCO2Desc: 'A massive amount of greenhouse gas (CO₂e) has been prevented by reducing waste.',
    impactKgSaved: 'kg of food saved',
    impactKgSavedDesc: '15.2 Tons (or 15,200 kg) of fresh ingredients have not been wasted.',
    impactVision: 'Sustainable Vision',
    impactEveryMeal: 'Every meal saved',
    impactStepForEarth: 'is a step for the Earth',
    impactVisionDesc: 'Food waste is not only an economic issue but a massive burden on the environment. When food is thrown away, all the energy and water used to grow, harvest, transport, and package it is also lost. By joining Remeli, you are part of a circular food supply chain where value is respected, and pressure on the Earth is reduced.',
    impactEnvTitle: 'Environmental Impact',
    impactReduce: 'Reduce',
    impactGreenhouse: 'Greenhouse Gases',
    impactEnvDesc: 'Food in landfills generates methane, a greenhouse gas 25 times more potent than CO₂. By rescuing food, we directly prevent global warming and protect clean air for future generations.',
    impactEconTitle: 'Economic Impact',
    impactOptimize: 'Optimize',
    impactResources: 'Resources',
    impactEconDesc: 'All ingredients, labor, and energy used to produce a meal are valuable. Remeli helps businesses recover production costs while providing users with quality meals at very reasonable prices.',
    impactSocialTitle: 'Social Impact',
    impactConnect: 'Connect',
    impactCommunity: 'Community',
    impactSocialDesc: 'Beyond buying and selling, Remeli is building a community of conscious consumers. We connect with each other and local stores through a positive message: Live green, consume smart, and value food.',
    impactBePart: 'Be part of',
    impactOfSolution: 'the solution',
    impactCtaDesc: 'Download Remeli today to start your journey of saving food and protecting the environment with tens of thousands of other Vietnamese.',
    impactCtaBtn: 'Download App Now',

    // Feedback
    fbCommunity: 'Remeli Community',
    fbVoice: 'Voice from',
    fbComm: 'the Community',
    fbDesc: 'Discover genuine experiences from thousands of customers and partners who have joined Remeli on the journey to fight food waste.',
    fbRealExp: 'Real Experiences',
    fbTitle1: 'Great food, great price!',
    fbText1: '"Super convenient app! I often order surprise bags from my favorite bakery at night. Good food, saves money, and feels like opening a surprise gift!"',
    fbRole1: 'User • HCMC',
    fbTitle2: 'End-of-month lifesaver',
    fbText2: '"As a student, Remeli really saves my wallet. The food is still hot and high quality. I hope more stores near my university join the app."',
    fbRole2: 'Student • Hanoi',
    fbTitle3: 'Anti-waste solution',
    fbText3: '"Since selling surplus food on Remeli, our restaurant no longer throws away food. Revenue went up slightly, but the best part is not wasting our cooking efforts."',
    fbRole3: 'Partner • District 3',
    fbTitle4: 'Small act, big meaning',
    fbText4: '"It feels great to help protect the environment every day just by eating good food. The app design is also very cute and easy to use!"',
    fbRole4: 'User • Da Nang',
    fbTitle5: 'Convenient and smooth',
    fbText5: '"The pickup feature works extremely well. I stop by the store after work, show the code, and get the food immediately without any waiting."',
    fbRole5: 'Office Worker • HCMC',
    fbTitle6: 'Joy of a baker',
    fbText6: '"No more headaches about unsold cakes every night. I am very grateful to the Remeli team for creating such a meaningful platform for society."',
    fbRole6: 'Bakery Owner • Hanoi',
"""

with open('script.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Insert after `regFormSubmit: 'Gửi thông tin đăng ký',`
content = content.replace("    regFormSubmit: 'Gửi thông tin đăng ký',\n", "    regFormSubmit: 'Gửi thông tin đăng ký',\n" + vi_strings)
content = content.replace("    regFormSubmit: 'Submit Registration',\n", "    regFormSubmit: 'Submit Registration',\n" + en_strings)

with open('script.js', 'w', encoding='utf-8') as f:
    f.write(content)
